import { ReactNode } from 'react';

import type { Metadata } from 'next';
import { Figtree } from 'next/font/google';

import { MainSidebar } from '../../../main/components/sidebar/MainSidebar';
import { SupabaseProvider } from '../../../../providers/SupabaseProvider';
import { UserProvider } from '../../../../providers/UserProvider';

import { HeadTitle } from '../../../main/components/helpers/HeadTitle';

import '../../../styles/globals.scss';
import { ModalProvider } from '../../../../providers/ModalProvider';

const font = Figtree({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Spotify Clone',
  description: 'Generated by create next app'
};

export function RootLayout({ children }: { children: ReactNode }) {
  return (
    <div className={font.className}>
      <HeadTitle text={metadata.title as string} />
      <SupabaseProvider>
        <UserProvider>
          <ModalProvider />
          <MainSidebar>{children}</MainSidebar>
        </UserProvider>
      </SupabaseProvider>
    </div>
  );
}

export default RootLayout;
