import { Figtree } from 'next/font/google';
import { Metadata } from 'next';

import { SupabaseProvider } from '../../providers/SupabaseProvider';
import { UserProvider } from '../../providers/UserProvider';
import { ModalProvider } from '../../providers/ModalProvider';
import { ToasterProvider } from '../../providers/ToasterProvider';

import { HeadTitle } from '../main/components/helpers/HeadTitle';
import { MainSidebar } from '../main/components/sidebar/MainSidebar';

import '../styles/globals.scss';

const font = Figtree({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Spotify Clone',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <HeadTitle text={metadata.title as string} />
        <ToasterProvider />
        <SupabaseProvider>
          <UserProvider>
            <ModalProvider />
            <MainSidebar>{children}</MainSidebar>
          </UserProvider>
        </SupabaseProvider>
      </body>
    </html>
  );
}
